const skills = [
    {name: 'JavaScript', level: 9, type: 'technical'},
    {name: 'Node.js', level: 9, type: 'technical'},
    {name: 'React.js', level: 9, type: 'technical'},
    {name: 'Express', level: 9, type: 'technical'},
    {name: 'Web E-Commerce', level: 9, type: 'technical'},
    {name: 'Mobile Development', level: 9, type: 'technical'},
    {name: 'Progressive Web Applications', level: 9, type: 'technical'},
    {name: 'PubNub', level: 9, type: 'technical'},
    {name: 'React Native', level: 6, type: 'technical'},
    {name: 'Voice A.I.', level: 5, type: 'technical'},
    {name: 'Webpack', level: 8, type: 'technical'},
    {name: 'GraphQL', level: 8, type: 'technical'},
    {name: 'Apollo', level: 6, type: 'technical'},
    {name: 'Java', level: 6, type: 'technical'},
    {name: 'Apache Sling', level: 6, type: 'technical'},
    {name: 'OSGi', level: 6, type: 'technical'},
    {name: 'Adobe Experience Manager', level: 9, type: 'technical'},
    {name: 'Ruby & Ruby on Rails', level: 9, type: 'technical'},
    {name: 'Python', level: 6, type: 'technical'},
    {name: 'Linux', level: 9, type: 'technical'},
    {name: 'Adobe XD', level: 6, type: 'non-technical'},
    {name: 'Agile Scrum', level: 8, type: 'non-technical'},
    {name: 'Leadership', level: 8, type: 'non-technical'},
    {name: 'Test Driven Development (TDD)', level: 8, type: 'technical'},
    {name: 'Internet of Things', level: 6, type: 'technical'},
    {name: 'UX Design', level: 6, type: 'non-technical'},
    {name: 'Marketing', level: 6, type: 'non-technical'},
    {name: 'Project Management', level: 6, type: 'non-technical'},
    {name: 'HTML5', level: 6, type: 'technical'},
    {name: 'CSS Modules', level: 6, type: 'technical'},
    {name: 'Angular JS', level: 7, type: 'technical'},
];

export default skills;
